name: macavi
description: "Aplicacion de macavi."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  dots_indicator: ^4.0.1
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.4
  url_launcher: ^6.0.20
  http: ^1.3.0
  firebase_messaging: ^15.1.0
  shared_preferences: ^2.0.0
  cloud_firestore: ^5.0.0
  app_links: ^6.4.1 # FIX: Sincronizado con la versión que usa Codemagic
  intl: ^0.18.1


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logomacavi.png
    - assets/friedonion.jpg
    - assets/argenta.jpg
    - assets/cheese.jpg
    - assets/crispyonion.jpg
    - assets/diburguer.jpg
    - assets/laprovo.jpg
    - assets/macavi.jpg
    - assets/yankee.jpg
    - assets/bluecheese.jpg
    - assets/autentic.jpg
    - assets/burguir.jpg
    - assets/promo.jpg
    - assets/coca.jpg
    - assets/agua.jpg
    - assets/sprite.jpg
    - assets/cocazero.jpg
    - assets/icon/ic_launcher.png
    - assets/points.png
    - assets/M.png
    - assets/autentic2.jpg
    - assets/pantallacarga.jpg

  fonts:
    - family: NewGroteskSquare
      fonts:
        - asset: assets/fonts/NewGroteskSquare.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 700
    - family: Aktiv
      fonts:
        - asset: assets/fonts/AktivGrotesk-Light.ttf
          weight: 700

