// File generated by FlutterFire CLI (ajustado manualmente para Android).
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // Si vas a compilar Web, regenerá con `flutterfire configure`.
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions no soporta esta plataforma.',
        );
    }
  }

  // Placeholders seguros para Web/macOS (no afectan Android).
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'web-api-key',
    appId: 'web-app-id',
    messagingSenderId: 'web-sender-id',
    projectId: 'macavi-96e80',
    authDomain: 'macavi-96e80.firebaseapp.com',
    storageBucket: 'macavi-96e80.appspot.com',
  );

  // ✅ Android real, tomado de android/app/google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfclKPl066EZPPHiIa15-EyyTxGYzM2yk',
    appId: '1:1049571319674:android:1e800d292f5223108f00c3',
    messagingSenderId: '1049571319674',
    projectId: 'macavi-96e80',
    storageBucket: 'macavi-96e80.appspot.com',
  );

  // Placeholders seguros para iOS/macOS (no afectan Android).
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'ios-api-key',
    appId: '1:1049571319674:ios:app-id',
    messagingSenderId: '1049571319674',
    projectId: 'macavi-96e80',
    storageBucket: 'macavi-96e80.appspot.com',
    iosBundleId: 'com.Macavi.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'macos-api-key',
    appId: '1:1049571319674:macos:app-id',
    messagingSenderId: '1049571319674',
    projectId: 'macavi-96e80',
    storageBucket: 'macavi-96e80.appspot.com',
    iosBundleId: 'com.Macavi.app',
  );
}
