// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAfclKPl066EZPPHiIa15-EyyTxGYzM2yk",
    authDomain: "your-web-auth-domain",
    projectId: "your-project-id",
    storageBucket: "your-storage-bucket",
    messagingSenderId: "your-messaging-sender-id",
    appId: "your-web-app-id",
    measurementId: "your-web-measurement-id",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AlzaSyAfcIKPl06EZPPHila15EyyTxGY2M2yk",
    authDomain: "macavi-96e80.firebaseapp.com",
    projectId: "macavi-96e80",
    storageBucket: "macavi-96e80.appspot.com",
    messagingSenderId: "1049571319674",
    appId: "1:1049571319674:android:1e800d292f5223108f00c3", // ✅ App ID Android
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AlzaSyAfcIKPl06EZPPHila15EyyTxGY2M2yk",
    authDomain: "macavi-96e80.firebaseapp.com",
    projectId: "macavi-96e80",
    storageBucket: "macavi-96e80.appspot.com",
    messagingSenderId: "1049571319674",
    appId: "1:1049571319674:ios:9838ccde80ad3c5a8f00c3", // ✅ App ID iOS
    iosClientId: "TU_IOS_CLIENT_ID", // 📌 FALTA copiar el iOS Client ID desde Firebase Console
    iosBundleId: "com.Macavi.app",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "your-macos-api-key",
    authDomain: "your-macos-auth-domain",
    projectId: "your-project-id",
    storageBucket: "your-storage-bucket",
    messagingSenderId: "your-messaging-sender-id",
    appId: "your-macos-app-id",
    iosClientId: "your-macos-ios-client-id",
    iosBundleId: "your-macos-bundle-id",
  );
}
